Using Redmine-API, Translation, Comment Todo (#)

diff --git a/.todo.actions.d/addredmine b/.todo.actions.d/addredmine
--- a/.todo.actions.d/addredmine
+++ b/.todo.actions.d/addredmine
@@ -1,14 +1,14 @@
 #!/bin/sh
-# Author: mwessjoh
+# Author: MarkusWessjohann
 # Date: 02.11.2016
-# Desc: Erstellt aus einer Redmine-Ticket-ID ein TODO-Eintrag
+# Desc: creates a task from a redmine-Ticket-File
 
-USAGE="addred Ticket-ID"
+USAGE="addred issue-ID"
 
 if [ $1 = usage ]; then
 	cat <<EOF
     $USAGE
-      Add Redmine-Ticket as task.
+      Add Redmine-issue as task.
 
 EOF
 exit
@@ -18,13 +18,38 @@ fi
 shift
 ID=$1
 
-redticketdata=`cat $TODO_DIR/Redmine/alle-Tickets.csv | grep "^${ID};" `
-thema=`echo "$redticketdata" | cut -f2 -d";"` 
-projekt=`echo "$redticketdata" | cut -f3 -d";" | tr " " "_"` 
-status=`echo "$redticketdata" | cut -f5 -d";"` 
-zugewiesen=`echo "$redticketdata" | cut -f6 -d";"` 
+user_pass=`cmd /C "gpg2.exe -d c:\\cygwin64\\home\\mwessjoh\\.redmine.conf.gpg" | \
+  grep -v "Codepage" | \
+  tr -d "$ ;"`
+user=` echo "$user_pass" | \
+  grep user | \
+  cut -f2 -d"=" | \
+  tr -d '"'`
+password=` echo "$user_pass" | \
+  grep pass | \
+  cut -f2 -d"=" | \
+  tr -d '"'`
+
+curl  -H "Content-Type: application/xml" -u "$user:$password" -X GET "http://redmine.ao-intranet/issues/${ID}.xml" > /tmp/$ID.xml
+
+#redticketdata=`cat $TODO_DIR/Redmine/alle-Tickets.csv | grep "^${ID};" `
+thema=`xmllint.exe --xpath "string(//subject)" /tmp/$ID.xml`
+projekt=`xmllint.exe --xpath "string(//project/@name)" /tmp/$ID.xml | tr " " "_"`
+status=`xmllint.exe --xpath "string(//status/@name)" /tmp/$ID.xml`
+zugewiesen=`xmllint.exe --xpath "string(//assigned_tp/@name)" /tmp/$ID.xml`
 prio="(A)"
 
+if [ "x$thema" == "x" ]
+then
+  echo "Redmine-issue not found: ${ID}";
+  exit 1
+fi
+$TODO_FULL_SH list | grep "#$ID" 2>&1 >/dev/null
+if [ "$?" -eq 0 ]
+then
+  echo "Redmine-issue already as Task (#$ID"
+  exit 1
+fi
 todo="$prio #$ID - $thema +$projekt @Redmine"
 $TODO_FULL_SH add "$todo"
 
diff --git a/.todo.actions.d/navred b/.todo.actions.d/navred
--- a/.todo.actions.d/navred
+++ b/.todo.actions.d/navred
@@ -1,12 +1,14 @@
 #!/bin/bash
-
+# Author: MarkusWessjohann
+# Date: 01.01.2017
+# Desc: Opens Browser form a redmine-issue-ID
 action=$1
 shift
 
 function usage(){
   echo "  Navigate to URL:"
-  echo "    nav ITEM#"
-  echo "      Searches for a URL in the todo line and launches a browser."
+  echo "    navred ITEM#"
+  echo "      Searches for a Redmine-Ticket-ID in the todo line and launches a browser."
   echo ""
   exit
 }
@@ -18,22 +20,18 @@ if ! [[ "$1" =~ ^[0-9]+$ ]]; then
     usage
 fi
 
-URL=$(sed "$1!d" "$TODO_FILE"|grep -E -o "([a-z]*)://[^ ]+")
-if [ "$URL" = "" ]; then
-  LINE=$(sed "$1!d" "$TODO_FILE")
-  if [ "$LINE" = "" ]; then
-    echo "Error, no item #$1 found!"
-  else
-    REDID=$(sed "$1!d" "$TODO_FILE"|grep -E -o " #[0-9]*[^ ]+")
-    if [ "$REDID" = "" ]; then
-      echo "Error, no URL seen in item #$1!"
-      echo "$LINE"
+ID=$(sed "$1!d" "$TODO_FILE"|grep -E -o "#[0-9]*"| tr -d "#")
+if [ "$ID" = "" ]; then
+    LINE=$(sed "$1!d" "$TODO_FILE")
+    if [ "$LINE" = "" ]; then
+        echo "Error, no item $1 found!"
     else
-      $TODO_FULL_SH navred "$1"
+        echo "Error, no Redmine-Ticket-ID seen in item $1!"
+        echo "$LINE"
     fi
-  fi
-  exit 1
+    exit 1
 fi
+URL="http://redmine.ao-intranet/issues/$ID"
 
 # Trying to be smart...
 # on Debian alike:
@@ -47,7 +45,7 @@ elif [ -x /usr/lib/git-core/git-web--browse ]; then
     cd /usr/lib/git-core && ./git-web--browse "$URL"
 # last resort, a la mano...
 elif $(which firefox >/dev/null 2>&1); then
-    exec firefox "$URL"
+    exec firefox -new-tab "$URL"
 elif $(which konqueror >/dev/null 2>&1); then
     exec konqueror "$URL"
 elif $(which nautilus >/dev/null 2>&1); then
